spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/logstation
#    username: root
#    password: admin
#  data:
#    elasticsearch:
#      cluster-nodes: localhost:9200
#      cluster-name: my-application
#      repositories:
#        enabled: true


server:
  port: 8088
  context-path: /

transport-client:
  cluster-name: my-application
  host: localhost
  port: 9300